# This is a basic workflow to help you get started with Actions

name: mast

# Controls when the workflow will run test
on:
  push:
    branches: [ dev_branch ]
  # Triggers the workflow on push or pull request events but only for the master branch
  # issue_comment:
  #   types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Debug with tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
